name : deploy to the staging 
on: 
    push:
        branches: [main]

jobs:
    redeploy_everything: 
        runs-on: ubuntu-latest
        name: redeploy_everything_on_main

        steps:
            - uses: actions/checkout@v3
              env :
                PRIVATE_KEY: ${{secrets.SSH_SECRET}}
                HOST_IP: ${{secrets.HOST_IP}}
                USERNAME: ${{secrets.USERNAME}}

            - run : |
                    echo "${{secrets.SSH_SECRET}}" > private_key.pem
                    chmod 700 private_key.pem

                    ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@20.244.44.37 -t '

                        cd ./demo-full-stack-app &&
                        git pull origin main &&
                        pnpm install  &&
                        pnpm run build &&
                        
                        export PATH=/home/ubuntu/.nvm/versions/node/v24.10.0/bin && 

                        pm2 start fe-app &&
                        pm2 start ws-app &&
                        pm2 start http-app
                    '


